name: thisexactmoment
favicon: null
layout_spectrum: 0.71589
typography_spectrum: 0.3673527578357607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75791708-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2955a5'
    - '#ef921c'
    - '#bfbfbf'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.4723143563605845
  rhythmicContrast: 0.7583968080580235
purpose: []
